version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "koppiapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vyipdg2zr567"
s3_prefix = "koppiapp"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

